- name: Variables from files
  hosts: mongodb
  vars_files:
    - variables.yaml
  tasks:
  - name: printing variables
    ansible.buildin.debug:
      msg: "My name is {{NAME}}, doing my {{COURSE}} course with {{TRAINER}}, mode is {{}} and Duration is {{DURATION}}"