- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print the user output
    ansible.builtin.debug:
      msg: "Output is: {{output}}" 
  - name: print rc status
    ansible.builtin.debug:
      msg: "Print RC status:{{output.rc}}"
  - name: craete user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0