- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print the user output
    ansible.builtin.debug:
      msg: "Output is: '{{user_output}}'" 
  - name: print rc status
    ansible.bulitin.debug:
      msg: "Print RC status:{{user_output.rc}}"